[package]
authors = ["Brandon Lewis <dotsony@gmail.com>"]
edition = "2018"
name = "udashboard"
version = "0.1.0"
[dependencies]
ron = "*"
drm-rs = "*"

[dependencies.cairo-rs]
features = ["png"]
version = "^0"

[dependencies.serde]
features = ["derive"]
version = "1.0"
