[package]
authors = ["Brandon Lewis <dotsony@gmail.com>"]
edition = "2018"
name = "udashboard"
version = "0.1.0"
[dependencies]
drm-rs = "*"
serde = {version = "1.0", features = ["derive"]}
ron = "*"
